version: "3.9"
services:
  purchase_service:
    build: ./project/purchase_service
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db_purchase
    volumes: 
      - ./project/purchase_service/migrations:/usr/src/app/migrations
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    environment:
      - DATABASE_URL=postgres+psycopg2://admin:123456@db_purchase:5432/database
    entrypoint: ["sh", "./entrypoint.sh"]
  shop_service:
    build: ./project/shop_service
    restart: always
    ports: 
      - 5001:5001
    depends_on:
      - db_shop
    volumes: 
      - ./project/shop_service/migrations:/usr/src/app/migrations
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    environment:
      - DATABASE_URL=postgres+psycopg2://admin:123456@db_shop:5432/database
    entrypoint: ["sh", "./entrypoint.sh"]
  factory:
    build: ./project/factory
    restart: always
    ports: 
      - 5003:5003
    depends_on:
      - db_factory
    volumes: 
      - ./project/factory/migrations:/usr/src/app/migration
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    environment:
      - DATABASE_URL=postgres+psycopg2://admin:123456@db_factory:5432/database
    entrypoint: ["sh", "./entrypoint.sh"]
  db_purchase:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
    volumes: 
      - pgpurchase:/var/lib/postgresql/data
  db_shop:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
    volumes: 
      - pgshop:/var/lib/postgresql/data
  db_factory:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
    volumes: 
      - pgfactory:/var/lib/postgresql/data
volumes: 
  pgshop:
  pgpurchase:
  pgfactory: