version: "3.9"
services:
  purchase_service:
    image: shmyaks/purchase
    build: ./project/purchase_service
    restart: always
    ports:
      - 5000:5000
    volumes: 
      - ./project/purchase_service/migrations/:/usr/src/app/migrations/
      - ./project/purchase_service/database/:/usr/src/app/database/
  shop_service:
    image: shmyaks/shop
    build: ./project/shop_service
    restart: always
    ports: 
      - 5001:5001
    volumes: 
      - ./project/shop_service/migrations/:/usr/src/app/migrations/
      - ./project/shop_service/database/:/usr/src/app/database/
  factory:
    image: shmyaks/factory
    build: ./project/factory
    restart: always
    ports: 
      - 5002:5002
    volumes: 
      - ./project/factory/migrations/:/usr/src/app/migrations/
      - ./project/factory/database/:/usr/src/app/database/
  nginx:
    image: nginx:alpine
    volumes:
      - ./project/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
    - factory
    - purchase_service
    - shop_service