"""empty message

Revision ID: b0b50ba5bb3e
Revises: 
Create Date: 2021-03-18 19:58:28.016195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b50ba5bb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('second_name', sa.String(length=32), nullable=True),
    sa.Column('login', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date_registration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_category',
    sa.Column('user_category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_category_name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_category_id')
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('full_price', sa.Integer(), nullable=True),
    sa.Column('purchase_name', sa.String(length=32), nullable=True),
    sa.Column('date_purchase', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_category_id', sa.Integer(), nullable=True),
    sa.Column('payment', sa.String(length=16), nullable=True),
    sa.Column('check_id_shop', sa.Integer(), nullable=True),
    sa.Column('category_shop', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('category_id_shop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_category_id'], ['user_category.user_category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('purchase_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.purchase_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_items')
    op.drop_table('purchase')
    op.drop_table('user_category')
    op.drop_table('users')
    # ### end Alembic commands ###
