"""empty message

Revision ID: d0d8e9876bab
Revises: 
Create Date: 2021-03-18 19:58:02.110145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d8e9876bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('shop',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=64), nullable=True),
    sa.Column('shop_phone', sa.String(length=16), nullable=True),
    sa.Column('shop_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('TableCategory',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.shop_id'], )
    )
    op.create_table('check',
    sa.Column('check_id_database', sa.Integer(), nullable=False),
    sa.Column('check_id_shop', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('category_id_shop', sa.Integer(), nullable=True),
    sa.Column('date_purchase', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id_shop'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.shop_id'], ),
    sa.PrimaryKeyConstraint('check_id_database')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['shop.shop_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('check')
    op.drop_table('TableCategory')
    op.drop_table('shop')
    op.drop_table('category')
    # ### end Alembic commands ###
